name: Run test
on:
  pull_request:
    branches:
      - dev
jobs:
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run test
        run: yarn test
